//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YobaLoncher {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YobaLoncher.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 11.11.2020T16:50:23,27 
        ///.
        /// </summary>
        internal static string BuildDate {
            get {
                return ResourceManager.GetString("BuildDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BBLoncher
        ///---========---
        ///1.0.5
        ///---========---
        ///BBLöncher {2} (YL v.{0}-{1})
        ///
        ///Лаунчер для Battle Brothers с русификатором от ZoG
        ///
        ///Автор билда: Hy60koshk
        ///---========---
        ///
        ///Через приложение BBLoncher мы не собираем совершенно никакой информации о пользователях.
        ///Все взаимодействия с сетью осуществляются только для получения от сервера информации, необходимой для работы лаунчера, и для скачивания обновлений игры и модов к ней. Наружу ничего не отправляется, даже информация о состоянии самого лаунчера.
        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string BuildTargetOpts {
            get {
                return ResourceManager.GetString("BuildTargetOpts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap green_dot {
            get {
                object obj = ResourceManager.GetObject("green_dot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///LaunchBtn = Запустить!
        ///UpdateBtn = Обновить
        ///OK = OK
        ///Yes = Да
        ///No = Нет
        ///Done = Готово
        ///Proceed = Продолжить
        ///Cancel = Отмена
        ///Close = Закрыть
        ///Minimize = Свернуть
        ///Help = Помощь
        ///About = О программе
        ///Apply = Применить
        ///Quit = Выйти
        ///Retry = Повторить
        ///RunOffline = Оффлайн-режим
        ///Browse = Обзор...
        ///ChangelogBtn = История изменений
        ///LinksBtn = Полезные ссылки
        ///StatusBtn = Состояние файлов
        ///SettingsBtn = Настройки
        ///ChangelogTooltip = Показать список изменений
        ///StatusTooltip = Показать результаты проверки  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string locale_default {
            get {
                return ResourceManager.GetString("locale_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] lucida_sans_unicode {
            get {
                object obj = ResourceManager.GetObject("lucida_sans_unicode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap red_dot {
            get {
                object obj = ResourceManager.GetObject("red_dot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&apos;Content-Type&apos; content=&apos;text/html; charset=UTF-8&apos; /&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=11&quot; /&gt;
        ///    &lt;title&gt;Yoba Löncher&lt;/title&gt;
        ///
        ///    &lt;script&gt;
        ///        /*var indexraw = &apos;[[[CHANGELOG]]]&apos;;
        ///
        ///        var index = [];
        ///        var indesplit = indexraw.split(&apos;=====|=|=|=====&apos;);
        ///        for (var i = 0; i &lt; indesplit.length; i++) {
        ///        var pair = indesplit[i].split(&apos;=====Content=====&apos;);
        ///        index.push({ Title: pair[0], Content: p [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string status_template {
            get {
                return ResourceManager.GetString("status_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap yellow_dot {
            get {
                object obj = ResourceManager.GetObject("yellow_dot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        internal static System.Drawing.Icon yIcon {
            get {
                object obj = ResourceManager.GetObject("yIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
